services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: devices-api
    depends_on:
    - db
    build:
      context: .
      dockerfile: API/Dockerfile
  db:
    image: postgres:18.1
    container_name: db
    restart: unless-stopped
    # shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d devices"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
    - pgdata:/var/lib/postgresql/18/docker
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

volumes:
  pgdata:
